---
- name: Install dependencies
  apt:
    pkg:
    - openjdk-21-jre-headless
    - adb
    - libturbojpeg
    - libavcodec58

    # Update the apt cache
    update_cache: true

    # Clean up after installation
    clean: true

- name: Configure udev rules for Android devices
  ansible.builtin.file:
    src: /lib/udev/rules.d/51-android.rules
    dest: /etc/udev/rules.d/51-android.rules
    state: link
