---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  vars:
    epgw_url_arm64: https://assets.eggplantsoftware.com/gateway/epgw.4.25.39.linux-arm64.tar.gz
    epgw_hash_arm64: sha256:71ced40b94053f2ab8292005126d1ae5d37f09d37a9c4ce5a6e6afc6bd63a276

    epgw_url_x64: https://assets.eggplantsoftware.com/gateway/epgw.4.25.39.linux-x64.tar.gz
    epgw_hash_x64: sha256:d63d84dc37124cd69282b7447351f0efc0ba761ae44f3eda69b29a6c23e64f3e

    keycloak_url: https://github.com/keycloak/keycloak/releases/download/26.0.7/keycloak-26.0.7.tar.gz
    keycloak_hash: sha1:82b65b4741378a9fda1fdd3556c7b3a58c8a4ebd

    quarkus_systemd_notify_url: https://repo1.maven.org/maven2/io/quarkiverse/systemd/notify/quarkus-systemd-notify/1.0.2/quarkus-systemd-notify-1.0.2.jar
    quarkus_systemd_notify_hash: sha1:3358e05408c5fe9983ed45ed443347316852aebc

    quarkus_systemd_notify_deployment_url: https://repo1.maven.org/maven2/io/quarkiverse/systemd/notify/quarkus-systemd-notify-deployment/1.0.2/quarkus-systemd-notify-deployment-1.0.2.jar
    quarkus_systemd_notify_deployment_hash: sha1:fddd14a0d21db557c18bd9176f3da6c788a52c26

    keycloak_bootstrap_admin_username: admin
    keycloak_bootstrap_admin_password: admin
  become: true

  tasks:
    - name: "Install dependencies ({{ ansible_distribution }})"
      include_tasks: "playbook.{{ ansible_distribution | lower }}.yml"

    - name: Determine if the Eggplant Gateway is installed
      ansible.builtin.stat:
        path: /opt/epgw/epgw
      register: epgw

    - name: Download Eggplant Gateway (arm64)
      ansible.builtin.get_url:
        url: '{{ epgw_url_arm64 }}'
        dest: '/tmp/epgw.tar.gz'
        checksum: '{{ epgw_hash_arm64 }}'
        mode: '644'
      when: ansible_architecture == "aarch64" and not epgw.stat.exists

    - name: Download Eggplant Gateway (x64)
      ansible.builtin.get_url:
        url: '{{ epgw_url_x64 }}'
        dest: '/tmp/epgw.tar.gz'
        checksum: '{{ epgw_hash_x64 }}'
        mode: '644'
      when: ansible_architecture == "x86_64" and not epgw.stat.exists

    - name: Create Eggplant Gateway directory
      ansible.builtin.file:
        path: /opt/epgw
        state: directory

    - name: Install Eggplant Gateway into /opt/epgw
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/epgw.tar.gz
        dest: /opt/epgw
      when: not epgw.stat.exists
      
    - name: Create /usr/local/bin/epgw symlink
      ansible.builtin.file:
        src: /opt/epgw/epgw
        dest: /usr/local/bin/epgw
        state: link

    - name: Create epgw user
      ansible.builtin.user:
        name: epgw

    - name: Creates /var/lib/epgw directory
      ansible.builtin.file:
        path: /var/lib/epgw
        state: directory
        owner: epgw
        mode: '0755'

    - name: Create epgw systemd service file
      template:
        src: epgw.service.j2
        dest: /lib/systemd/system/epgw.service

    - name: Determine if the Eggplant Gateway is installed
      ansible.builtin.stat:
        path: /opt/keycloak/bin/kc.sh
      register: keycloak

    - name: Download Keycloak
      ansible.builtin.get_url:
        url: '{{ keycloak_url }}'
        dest: '/tmp/keycloak.tar.gz'
        checksum: '{{ keycloak_hash }}'
        mode: '644'
      when: not keycloak.stat.exists

    - name: Create keycloak user
      ansible.builtin.user:
        name: keycloak

    - name: Create /opt/keycloak/ directory
      ansible.builtin.file:
        path: /opt/keycloak/
        state: directory
        owner: keycloak
        mode: '0755'

    - name: Install Keycloak into /opt/keycloak
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/keycloak.tar.gz
        dest: /opt/keycloak
        owner: keycloak
        # Remove the top-level directory
        extra_opts: ['--strip-components=1', '--show-stored-names']
      when: not keycloak.stat.exists

    - name: Download quarkus-systemd-notify-deployment
      ansible.builtin.get_url:
        url: '{{ quarkus_systemd_notify_url }}'
        dest: '/opt/keycloak/providers/'
        checksum: '{{ quarkus_systemd_notify_hash }}'
        mode: '644'

    - name: Download quarkus-systemd-notify-deployment
      ansible.builtin.get_url:
        url: '{{ quarkus_systemd_notify_deployment_url }}'
        dest: '/opt/keycloak/providers/'
        checksum: '{{ quarkus_systemd_notify_deployment_hash }}'
        mode: '644'

    - name: Create Keycloak systemd service file
      template:
        src: keycloak.service.j2
        dest: /lib/systemd/system/keycloak.service

    - name: Start Keycloak servce
      ansible.builtin.service:
        name: keycloak
        state: started
