---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: "Install dependencies ({{ ansible_distribution }})"
      include_tasks: "playbook.{{ ansible_distribution | lower }}.yml"
