name: rpi
on:
  push:
    branches: [ main ]
jobs:
  rpi:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu ]
    runs-on: ubuntu-latest
    container:
      image: mkaczanowski/packer-builder-arm
      volumes:
        - /dev:/dev
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Install ansible
        run: |
          apt update
          apt install software-properties-common gpg-agent --no-install-recommends -y
          add-apt-repository --yes --update ppa:ansible/ansible
          apt install ansible --no-install-recommends -y
          packer plugins install github.com/hashicorp/ansible
      - name: Build
        run: /entrypoint.sh build ${{ matrix.os }}.json
      - name: Compress
        run: gzip epgw-ubuntu-24.04.img
      - uses: actions/upload-artifact@v4
        with:
          name: epgw-ubuntu-24.04
          path: "*.img.gz"
